services:
  - type: psql
    name: policyportal-db
    plan: free
    databaseName: SPPolicyPortal
    user: postgres

  - type: web
    name: policyportal-api
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node src/index.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: policyportal-db
          property: connectionString
      - key: NODE_ENV
        value: production