# Corrected render.yaml with valid SQL identifiers

services:
  - type: web
    name: policyportal-api
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node src/index.js" # Make sure this command is correct for your project
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: policyportal-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: policyportal-db
    plan: free
    databaseName: sp_policy_portal       # CORRECTED: Lowercase with underscores
    user: policy_portal_user          # CORRECTED: A unique, non-reserved name